<a href="https://colab.research.google.com/github/shivamgoyal7/LinearRegression-ML/blob/master/climate%20action.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [73]:
dataset = pd.read_csv('temp.csv')
date = dataset.iloc[:, 0:1].values
X = dataset.iloc[:, 3:8].values
y = dataset.iloc[:, -1].values

In [74]:
print(date)

[['01/01/2019']
 ['02/01/2019']
 ['02/02/2019']
 ['02/03/2019']
 ['02/04/2019']
 ['02/05/2019']
 ['02/06/2019']
 ['02/07/2019']
 ['02/08/2019']
 ['02/09/2019']
 ['02/10/2019']
 ['02/11/2019']
 ['02/12/2019']
 ['02/13/2019']
 ['02/14/2019']
 ['02/15/2019']
 ['02/16/2019']
 ['02/17/2019']
 ['02/18/2019']
 ['02/19/2019']
 ['02/20/2019']
 ['02/21/2019']
 ['02/22/2019']
 ['02/23/2019']
 ['02/24/2019']
 ['02/25/2019']
 ['02/26/2019']
 ['02/27/2019']
 ['02/28/2019']
 ['03/01/2019']
 ['03/02/2019']
 ['03/03/2019']
 ['03/04/2019']
 ['03/05/2019']
 ['03/06/2019']
 ['03/07/2019']
 ['03/08/2019']
 ['03/09/2019']
 ['03/10/2019']
 ['03/11/2019']
 ['03/12/2019']
 ['03/13/2019']
 ['03/14/2019']
 ['03/15/2019']
 ['03/16/2019']
 ['03/17/2019']
 ['03/18/2019']
 ['03/19/2019']
 ['03/20/2019']
 ['03/21/2019']
 ['03/22/2019']
 ['03/23/2019']
 ['03/24/2019']
 ['03/25/2019']
 ['03/26/2019']
 ['03/27/2019']
 ['03/28/2019']
 ['03/29/2019']
 ['03/30/2019']
 ['03/31/2019']
 ['04/01/2019']
 ['04/02/2019']
 ['04/03

In [75]:
print(X)

[[7.10e-01 1.10e+01 1.72e+02 1.61e+01 1.01e+03]
 [7.20e-01 1.47e+01 2.95e+02 1.04e+01 1.01e+03]
 [7.20e-01 1.27e+01 3.10e+02 1.03e+01 1.01e+03]
 [7.40e-01 1.43e+01 3.01e+02 1.61e+01 1.01e+03]
 [7.90e-01 1.38e+01 3.04e+02 1.52e+01 1.01e+03]
 [8.20e-01 1.72e+01 2.91e+02 1.61e+01 1.01e+03]
 [8.00e-01 1.42e+01 3.00e+02 1.52e+01 1.01e+03]
 [7.80e-01 1.36e+01 3.12e+02 1.50e+01 1.01e+03]
 [8.00e-01 1.40e+01 3.09e+02 1.58e+01 1.01e+03]
 [8.00e-01 1.12e+01 3.00e+02 1.58e+01 1.01e+03]
 [8.40e-01 1.33e+01 3.01e+02 1.50e+01 1.01e+03]
 [7.80e-01 1.55e+01 3.10e+02 9.98e+00 1.01e+03]
 [7.80e-01 1.40e+01 3.09e+02 9.98e+00 1.01e+03]
 [7.90e-01 1.36e+01 3.02e+02 9.98e+00 1.01e+03]
 [7.70e-01 1.56e+01 2.99e+02 9.98e+00 1.01e+03]
 [7.70e-01 1.28e+01 2.99e+02 9.98e+00 1.01e+03]
 [7.40e-01 1.21e+01 3.00e+02 1.04e+01 1.01e+03]
 [7.20e-01 9.71e+00 2.99e+02 9.98e+00 1.01e+03]
 [6.20e-01 9.66e+00 2.72e+02 9.98e+00 1.01e+03]
 [6.20e-01 5.60e+00 2.85e+02 1.04e+01 1.01e+03]
 [6.20e-01 8.15e+00 2.84e+02 9.98e+00 1.

In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [77]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [78]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[11.2  11.12]
 [14.71 16.04]
 [13.31 12.13]
 [ 9.82  8.88]
 [15.08 15.97]
 [20.8  19.81]
 [12.34 12.14]
 [17.68 17.9 ]
 [11.09  9.93]
 [18.66 17.3 ]
 [12.21 10.09]
 [20.11 19.83]
 [13.59 13.68]
 [10.99  9.81]
 [11.43 10.36]
 [ 7.41  8.08]
 [17.45 17.26]
 [14.66 15.07]
 [ 7.27  4.89]
 [10.83  9.91]
 [23.08 22.6 ]
 [15.01 16.06]
 [12.48 11.55]
 [21.77 21.23]
 [22.98 22.82]
 [20.18 18.93]
 [10.86 10.49]
 [15.44 13.84]
 [14.48 13.31]
 [14.92 15.56]
 [ 7.01  7.81]
 [11.22 10.77]
 [18.33 19.28]
 [21.62 23.79]
 [14.73 13.24]
 [ 9.11  9.88]
 [15.8  14.95]
 [10.35  9.29]
 [17.39 18.77]
 [15.99 17.08]]


In [79]:
accuracy = regressor.score(X_test, y_test)
accuracy

0.945486076049944