<a href="https://colab.research.google.com/github/shivamgoyal7/LinearRegression-ML/blob/master/stockPricePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **STOCK PRICE PREDICTION**

In [14]:
!pip install quandl

In [15]:
#Quandl unifies financial and economic datasets from hundreds of publishers on a single user-friendly platform.

import quandl
import numpy as np

In [16]:
#amazon dataset is used here

dataset = quandl.get("WIKI/AMZN")
dataset

Open     High      Low  ...     Adj. Low   Adj. Close  Adj. Volume
Date                                   ...                                       
1997-05-16    22.38    23.75    20.50  ...     1.708333     1.729167   14700000.0
1997-05-19    20.50    21.25    19.50  ...     1.625000     1.708333    6106800.0
1997-05-20    20.75    21.00    19.63  ...     1.635833     1.635833    5467200.0
1997-05-21    19.25    19.75    16.50  ...     1.375000     1.427500   18853200.0
1997-05-22    17.25    17.38    15.75  ...     1.312500     1.395833   11776800.0
...             ...      ...      ...  ...          ...          ...          ...
2018-03-21  1586.45  1590.00  1563.17  ...  1563.170000  1581.860000    4667291.0
2018-03-22  1565.47  1573.85  1542.40  ...  1542.400000  1544.100000    6177737.0
2018-03-23  1539.01  1549.02  1495.36  ...  1495.360000  1495.560000    7843966.0
2018-03-26  1530.00  1556.99  1499.25  ...  1499.250000  1555.860000    5547618.0
2018-03-27  1572.40  1575.96  1482.32  ...  1482.320000  1497.050000    6793279.0

[5248 rows x 12 columns]

In [17]:
#added a new column of 'Prediction' at the end to predict stock price

dataset['Prediction'] = dataset[['Adj. Close']].shift(-30)
dataset

Open     High      Low  ...   Adj. Close  Adj. Volume  Prediction
Date                                   ...                                      
1997-05-16    22.38    23.75    20.50  ...     1.729167   14700000.0    1.541667
1997-05-19    20.50    21.25    19.50  ...     1.708333    6106800.0    1.515833
1997-05-20    20.75    21.00    19.63  ...     1.635833    5467200.0    1.588333
1997-05-21    19.25    19.75    16.50  ...     1.427500   18853200.0    1.911667
1997-05-22    17.25    17.38    15.75  ...     1.395833   11776800.0    2.000000
...             ...      ...      ...  ...          ...          ...         ...
2018-03-21  1586.45  1590.00  1563.17  ...  1581.860000    4667291.0         NaN
2018-03-22  1565.47  1573.85  1542.40  ...  1544.100000    6177737.0         NaN
2018-03-23  1539.01  1549.02  1495.36  ...  1495.560000    7843966.0         NaN
2018-03-26  1530.00  1556.99  1499.25  ...  1555.860000    5547618.0         NaN
2018-03-27  1572.40  1575.96  1482.32  ...  1497.050000    6793279.0         NaN

[5248 rows x 13 columns]

In [18]:
# x is column start from 0 to -1

x = np.array(dataset.drop(['Prediction'], 1))
x = x[: -30]
x

array([[2.23800000e+01, 2.37500000e+01, 2.05000000e+01, ...,
        1.70833333e+00, 1.72916667e+00, 1.47000000e+07],
       [2.05000000e+01, 2.12500000e+01, 1.95000000e+01, ...,
        1.62500000e+00, 1.70833333e+00, 6.10680000e+06],
       [2.07500000e+01, 2.10000000e+01, 1.96300000e+01, ...,
        1.63583333e+00, 1.63583333e+00, 5.46720000e+06],
       ...,
       [1.42967000e+03, 1.43375000e+03, 1.34994000e+03, ...,
        1.34994000e+03, 1.35047000e+03, 8.10856000e+06],
       [1.37349000e+03, 1.38350000e+03, 1.26593000e+03, ...,
        1.26593000e+03, 1.33899000e+03, 1.37878860e+07],
       [1.36467000e+03, 1.39381000e+03, 1.34401000e+03, ...,
        1.34401000e+03, 1.38623000e+03, 6.68221400e+06]])

In [19]:
y = np.array(dataset['Prediction'])
y = y[: -30]
y

array([1.54166667e+00, 1.51583333e+00, 1.58833333e+00, ...,
       1.49556000e+03, 1.55586000e+03, 1.49705000e+03])

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

# **Linear Regression**

In [30]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
#comparing y_test and y_pred

y_pred = regressor.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[  48.77623605   51.98      ]
 [  89.91277196   72.08      ]
 [ 120.92958903  136.579     ]
 ...
 [   5.06923379   14.72      ]
 [1061.14864383  999.855     ]
 [  45.92019632   59.59      ]]


# **ACCURACY SCORE**

In [32]:
accuracy = regressor.score(x_test, y_test)
accuracy

0.9892536013136081

In [33]:
remaining_x = np.array(dataset.drop(['Prediction'], 1))[-30:]
remaining_x

array([[1.385930e+03, 1.419720e+03, 1.383530e+03, 1.414510e+03,
        5.858860e+06, 0.000000e+00, 1.000000e+00, 1.385930e+03,
        1.419720e+03, 1.383530e+03, 1.414510e+03, 5.858860e+06],
       [1.406250e+03, 1.452060e+03, 1.403360e+03, 1.451050e+03,
        5.881238e+06, 0.000000e+00, 1.000000e+00, 1.406250e+03,
        1.452060e+03, 1.403360e+03, 1.451050e+03, 5.881238e+06],
       [1.466890e+03, 1.468940e+03, 1.436840e+03, 1.461760e+03,
        5.598111e+06, 0.000000e+00, 1.000000e+00, 1.466890e+03,
        1.468940e+03, 1.436840e+03, 1.461760e+03, 5.598111e+06],
       [1.457370e+03, 1.465800e+03, 1.446560e+03, 1.448690e+03,
        4.410879e+06, 0.000000e+00, 1.000000e+00, 1.457370e+03,
        1.465800e+03, 1.446560e+03, 1.448690e+03, 4.410879e+06],
       [1.446490e+03, 1.488770e+03, 1.446490e+03, 1.468350e+03,
        6.388374e+06, 0.000000e+00, 1.000000e+00, 1.446490e+03,
        1.488770e+03, 1.446490e+03, 1.468350e+03, 6.388374e+06],
       [1.485000e+03, 1.503490e+03,

In [34]:
#prediction of the last 30 dataset

new_y = regressor.predict(remaining_x)
new_y

array([1502.67127469, 1545.3979061 , 1565.0160193 , 1535.52051514,
       1553.33191543, 1569.01839397, 1579.05797806, 1595.29076826,
       1615.35968735, 1606.97393174, 1601.60899203, 1603.72124011,
       1602.88928906, 1626.57594229, 1631.73316289, 1641.86183701,
       1646.4966961 , 1677.8928154 , 1696.3178362 , 1695.17932549,
       1684.52641203, 1681.45162218, 1668.89637549, 1649.66481668,
       1689.39136073, 1688.04284266, 1639.6161701 , 1591.79180058,
       1671.77949431, 1611.72291414])